version: "3.7"
services:
  php:
    build:
      context: .
    volumes:
      - ..:/workspace
    command: apache2-foreground
    environment:
      - DB_DSN=mysql:host=db;port=3306;dbname=poll;
      - DB_USER=root
      - DB_PASS=kr0sb3n
    ports:
      - 8080:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=kr0sb3n
      - MYSQL_DATABASE=poll
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ../data:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
